// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.GraphQLClients.BlazorWAS.DuyenCTT.Models;

public partial class AppointmentMinhPp
{
    public int AppointmentMinhPpid { get; set; }

    public int? UserId { get; set; }

    public int? ConsultantId { get; set; }

    public DateOnly? ScheduledDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public virtual ConsultantMinhPp Consultant { get; set; }

    public virtual User User { get; set; }
}