// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.GraphQLClients.BlazorWAS.DuyenCTT.Models;


public partial class ConsultantAvailability
{
    public int AvailabilityId { get; set; }

    public int? ConsultantId { get; set; }

    public DateOnly? AvailableDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public virtual ConsultantMinhPp Consultant { get; set; }
}