// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.GraphQLClients.BlazorWAS.DuyenCTT.Models;
public partial class SurveyResultDuongNd
{
    public int ResultDuongNdid { get; set; }

    public int SurveyId { get; set; }

    public int UserId { get; set; }

    public DateTime? TakenAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public string Status { get; set; }

    public decimal? TotalScore { get; set; }

    public string Recommendation { get; set; }

    public string Ipaddress { get; set; }

    public string UserAgent { get; set; }

    public int? DurationSeconds { get; set; }

    public string ReviewStatus { get; set; }

    public int? ReviewedByUserId { get; set; }

    public string ReviewComments { get; set; }

    public virtual User ReviewedByUser { get; set; }

    public virtual SurveyDuongNd Survey { get; set; }

    public virtual ICollection<SurveyAnswerDuongNd> SurveyAnswerDuongNds { get; set; } = new List<SurveyAnswerDuongNd>();

    public virtual User User { get; set; }
}