// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace DrugPrevention.GraphQLClients.BlazorWAS.DuyenCTT.Models;

public partial class SurveyQuestionManhPt
{
    public int QuestionId { get; set; }

    public int SurveyId { get; set; }

    public int? BankQuestionId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public int? DisplayOrder { get; set; }

    public bool? IsMandatory { get; set; }

    public decimal? PointsPossible { get; set; }

    public string HintText { get; set; }

    public int? PageNumber { get; set; }

    public string SectionTitle { get; set; }

    public int? ParentQuestionId { get; set; }

    public string ConditionsJson { get; set; }

    public virtual QuestionBank BankQuestion { get; set; }

    public virtual ICollection<SurveyQuestionManhPt> InverseParentQuestion { get; set; } = new List<SurveyQuestionManhPt>();

    public virtual SurveyQuestionManhPt ParentQuestion { get; set; }

    public virtual SurveyDuongNd Survey { get; set; }

    public virtual ICollection<SurveyAnswerDuongNd> SurveyAnswerDuongNds { get; set; } = new List<SurveyAnswerDuongNd>();

    public virtual ICollection<SurveyOptionManhPt> SurveyOptionManhPts { get; set; } = new List<SurveyOptionManhPt>();
}