// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
namespace DrugPrevention.GraphQLClients.BlazorWAS.DuyenCTT.Models;

public partial class SurveyAssignment
{
    public int SurveyAssignmentId { get; set; }

    public int SurveyId { get; set; }

    public int UserId { get; set; }

    public string RoleInSurvey { get; set; }

    public DateTime? AssignmentDate { get; set; }

    public string TaskDescription { get; set; }

    public bool? IsActiveAssignment { get; set; }

    public DateOnly? DueDate { get; set; }

    public virtual SurveyDuongNd Survey { get; set; }

    public virtual User User { get; set; }
}