// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.BusinessObject.Shared.Models.SE182661.Models;

public partial class CourseEnrollmentDuyenCtt
{
    public int EnrollmentDuyenCttid { get; set; }

    public int? UserId { get; set; }

    public int? CourseId { get; set; }

    public DateTime? EnrolledAt { get; set; }

    public int? Progress { get; set; }

    public DateTime? CompletedAt { get; set; }

    public decimal? Score { get; set; }

    public string CertificateUrl { get; set; }

    public bool? IsCertified { get; set; }

    public string EnrollmentSource { get; set; }

    public virtual CourseDuyenCtt Course { get; set; }

    //public virtual User User { get; set; }
}