// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DrugPrevention.BusinessObject.Shared.Models.SE182661.Models;
public partial class CourseDuyenCtt
{
    public int CourseDuyenCttid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string TargetGroup { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CourseEnrollmentDuyenCtt> CourseEnrollmentDuyenCtts { get; set; } = new List<CourseEnrollmentDuyenCtt>();
}
