// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class ConsultantMinhPp
{
    public int ConsultantMinhPpid { get; set; }

    public int? UserId { get; set; }

    public string Specialization { get; set; }

    public string Qualifications { get; set; }

    public string Bio { get; set; }

    public virtual ICollection<AppointmentMinhPp> AppointmentMinhPps { get; set; } = new List<AppointmentMinhPp>();

    public virtual ICollection<ConsultantAvailability> ConsultantAvailabilities { get; set; } = new List<ConsultantAvailability>();

    public virtual User User { get; set; }
}