// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class CourseDuyenCtt
{
    [Key]
    public int CourseDuyenCttid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string TargetGroup { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CourseEnrollmentDuyenCtt> CourseEnrollmentDuyenCtts { get; set; } = new List<CourseEnrollmentDuyenCtt>();
}