//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference4
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseEnrollmentPaginationResult", Namespace="http://schemas.datacontract.org/2004/07/DrugPrevention.Repositories.DuyenCTT.Soap" +
        "Models")]
    public partial class CourseEnrollmentPaginationResult : object
    {
        
        private ServiceReference4.CourseEnrollmentDuyenCttSoapModel[] ItemsField;
        
        private int PageIndexField;
        
        private int PageSizeField;
        
        private int TotalItemsField;
        
        private int TotalPagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference4.CourseEnrollmentDuyenCttSoapModel[] Items
        {
            get
            {
                return this.ItemsField;
            }
            set
            {
                this.ItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex
        {
            get
            {
                return this.PageIndexField;
            }
            set
            {
                this.PageIndexField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize
        {
            get
            {
                return this.PageSizeField;
            }
            set
            {
                this.PageSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TotalPages
        {
            get
            {
                return this.TotalPagesField;
            }
            set
            {
                this.TotalPagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CourseEnrollmentDuyenCttSoapModel", Namespace="http://schemas.datacontract.org/2004/07/DrugPrevention.Repositories.DuyenCTT.Soap" +
        "Models")]
    public partial class CourseEnrollmentDuyenCttSoapModel : object
    {
        
        private int EnrollmentDuyenCttidField;
        
        private System.Nullable<int> UserIdField;
        
        private System.Nullable<int> CourseIdField;
        
        private System.Nullable<System.DateTime> EnrolledAtField;
        
        private System.Nullable<int> ProgressField;
        
        private System.Nullable<System.DateTime> CompletedAtField;
        
        private System.Nullable<decimal> ScoreField;
        
        private string CertificateUrlField;
        
        private System.Nullable<bool> IsCertifiedField;
        
        private string EnrollmentSourceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EnrollmentDuyenCttid
        {
            get
            {
                return this.EnrollmentDuyenCttidField;
            }
            set
            {
                this.EnrollmentDuyenCttidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<int> CourseId
        {
            get
            {
                return this.CourseIdField;
            }
            set
            {
                this.CourseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<System.DateTime> EnrolledAt
        {
            get
            {
                return this.EnrolledAtField;
            }
            set
            {
                this.EnrolledAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<int> Progress
        {
            get
            {
                return this.ProgressField;
            }
            set
            {
                this.ProgressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.Nullable<System.DateTime> CompletedAt
        {
            get
            {
                return this.CompletedAtField;
            }
            set
            {
                this.CompletedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<decimal> Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string CertificateUrl
        {
            get
            {
                return this.CertificateUrlField;
            }
            set
            {
                this.CertificateUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public System.Nullable<bool> IsCertified
        {
            get
            {
                return this.IsCertifiedField;
            }
            set
            {
                this.IsCertifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string EnrollmentSource
        {
            get
            {
                return this.EnrollmentSourceField;
            }
            set
            {
                this.EnrollmentSourceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference4.ICourseEnrollmentDuyenCTTSoapService")]
    public interface ICourseEnrollmentDuyenCTTSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/GetAll", ReplyAction="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/GetAllResponse")]
        System.Threading.Tasks.Task<ServiceReference4.CourseEnrollmentPaginationResult> GetAllAsync(int page, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/GetById", ReplyAction="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/GetByIdResponse")]
        System.Threading.Tasks.Task<ServiceReference4.CourseEnrollmentDuyenCttSoapModel> GetByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/Search", ReplyAction="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/SearchResponse")]
        System.Threading.Tasks.Task<ServiceReference4.CourseEnrollmentPaginationResult> SearchAsync(string enrollmentSource, System.Nullable<double> score, string certificateUrl, int page, int size);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/Create", ReplyAction="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/CreateResponse")]
        System.Threading.Tasks.Task<int> CreateAsync(ServiceReference4.CourseEnrollmentDuyenCttSoapModel courseEnrollment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/Update", ReplyAction="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/UpdateResponse")]
        System.Threading.Tasks.Task<int> UpdateAsync(ServiceReference4.CourseEnrollmentDuyenCttSoapModel courseEnrollment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/Delete", ReplyAction="http://tempuri.org/ICourseEnrollmentDuyenCTTSoapService/DeleteResponse")]
        System.Threading.Tasks.Task<bool> DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICourseEnrollmentDuyenCTTSoapServiceChannel : ServiceReference4.ICourseEnrollmentDuyenCTTSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CourseEnrollmentDuyenCTTSoapServiceClient : System.ServiceModel.ClientBase<ServiceReference4.ICourseEnrollmentDuyenCTTSoapService>, ServiceReference4.ICourseEnrollmentDuyenCTTSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CourseEnrollmentDuyenCTTSoapServiceClient() : 
                base(CourseEnrollmentDuyenCTTSoapServiceClient.GetDefaultBinding(), CourseEnrollmentDuyenCTTSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICourseEnrollmentDuyenCTTSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseEnrollmentDuyenCTTSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CourseEnrollmentDuyenCTTSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), CourseEnrollmentDuyenCTTSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseEnrollmentDuyenCTTSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CourseEnrollmentDuyenCTTSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseEnrollmentDuyenCTTSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CourseEnrollmentDuyenCTTSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CourseEnrollmentDuyenCTTSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference4.CourseEnrollmentPaginationResult> GetAllAsync(int page, int size)
        {
            return base.Channel.GetAllAsync(page, size);
        }
        
        public System.Threading.Tasks.Task<ServiceReference4.CourseEnrollmentDuyenCttSoapModel> GetByIdAsync(int id)
        {
            return base.Channel.GetByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<ServiceReference4.CourseEnrollmentPaginationResult> SearchAsync(string enrollmentSource, System.Nullable<double> score, string certificateUrl, int page, int size)
        {
            return base.Channel.SearchAsync(enrollmentSource, score, certificateUrl, page, size);
        }
        
        public System.Threading.Tasks.Task<int> CreateAsync(ServiceReference4.CourseEnrollmentDuyenCttSoapModel courseEnrollment)
        {
            return base.Channel.CreateAsync(courseEnrollment);
        }
        
        public System.Threading.Tasks.Task<int> UpdateAsync(ServiceReference4.CourseEnrollmentDuyenCttSoapModel courseEnrollment)
        {
            return base.Channel.UpdateAsync(courseEnrollment);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteAsync(int id)
        {
            return base.Channel.DeleteAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICourseEnrollmentDuyenCTTSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICourseEnrollmentDuyenCTTSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7287/CourseEnrollmentDuyenCTTSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CourseEnrollmentDuyenCTTSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICourseEnrollmentDuyenCTTSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CourseEnrollmentDuyenCTTSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICourseEnrollmentDuyenCTTSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICourseEnrollmentDuyenCTTSoapService,
        }
    }
}
