// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class BlogMinhLh
{
    public int BlogMinhLhid { get; set; }

    public string Title { get; set; }

    public string Summary { get; set; }

    public string Content { get; set; }

    public int? AuthorId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Status { get; set; }

    public int? Views { get; set; }

    public string Tags { get; set; }

    public virtual User Author { get; set; }

    public virtual ICollection<BlogMinhLhcomment> BlogMinhLhcomments { get; set; } = new List<BlogMinhLhcomment>();
}