// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Runtime.Serialization;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

[DataContract]
public partial class SystemUserAccount
{
    [DataMember(Order = 1)]
    public int UserAccountId { get; set; }

    [DataMember(Order = 2)]
    public string UserName { get; set; }

    [DataMember(Order = 3)]
    public string Password { get; set; }

    [DataMember(Order = 4)]
    public string FullName { get; set; }

    [DataMember(Order = 5)]
    public string Email { get; set; }

    [DataMember(Order = 6)]
    public string Phone { get; set; }

    [DataMember(Order = 7)]
    public string EmployeeCode { get; set; }

    [DataMember(Order = 8)]
    public int RoleId { get; set; }

    [DataMember(Order = 9)]
    public string RequestCode { get; set; }

    [DataMember(Order = 10)]
    public DateTime? CreatedDate { get; set; }

    [DataMember(Order = 11)]
    public string ApplicationCode { get; set; }

    [DataMember(Order = 12)]
    public string CreatedBy { get; set; }

    [DataMember(Order = 13)]
    public DateTime? ModifiedDate { get; set; }

    [DataMember(Order = 14)]
    public string ModifiedBy { get; set; }

    [DataMember(Order = 15)]
    public bool IsActive { get; set; }
}
