// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class CommunityProgramKhoaNdd
{
    public int CommunityProgramKhoaNddid { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public string TargetGroup { get; set; }

    public DateTime? CreatedDate { get; set; }

    public DateTime? LastEditedDate { get; set; }

    public int? CreatedBy { get; set; }

    public int? EditedBy { get; set; }

    public virtual User CreatedByNavigation { get; set; }

    public virtual User EditedByNavigation { get; set; }

    public virtual ICollection<ProgramParticipantKhoaNdd> ProgramParticipantKhoaNdds { get; set; } = new List<ProgramParticipantKhoaNdd>();

    public virtual ICollection<ProgramSurvey> ProgramSurveys { get; set; } = new List<ProgramSurvey>();
}