// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class QuestionBank
{
    public int BankQuestionId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public string Category { get; set; }

    public string SubCategory { get; set; }

    public string SuggestedOptionsJson { get; set; }

    public int? CreatedByUserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? LastModifiedAt { get; set; }

    public int? Version { get; set; }

    public string Tags { get; set; }

    public bool? IsArchived { get; set; }

    public string LanguageCode { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<SurveyQuestionManhPt> SurveyQuestionManhPts { get; set; } = new List<SurveyQuestionManhPt>();
}