// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class Appointment
{
    public int AppointmentId { get; set; }

    public int? UserId { get; set; }

    public int? ConsultantId { get; set; }

    public DateOnly? ScheduledDate { get; set; }

    public TimeOnly? StartTime { get; set; }

    public TimeOnly? EndTime { get; set; }

    public string Status { get; set; }

    public string Notes { get; set; }

    public virtual Consultant Consultant { get; set; }

    public virtual User User { get; set; }
}