// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class Consultant
{
    public int ConsultantId { get; set; }

    public int? UserId { get; set; }

    public string Specialization { get; set; }

    public string Qualifications { get; set; }

    public string Bio { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<ConsultantAvailability> ConsultantAvailabilities { get; set; } = new List<ConsultantAvailability>();

    public virtual User User { get; set; }
}