// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class Course
{
    public int CourseId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string TargetGroup { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<CourseEnrollment> CourseEnrollments { get; set; } = new List<CourseEnrollment>();
}