// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class ProgramParticipant
{
    public int ProgramParticipantId { get; set; }

    public int? ProgramId { get; set; }

    public int? UserId { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual CommunityProgram Program { get; set; }

    public virtual User User { get; set; }
}