// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class SurveyQuestion
{
    public int QuestionId { get; set; }

    public int? SurveyId { get; set; }

    public string QuestionText { get; set; }

    public string QuestionType { get; set; }

    public virtual Survey Survey { get; set; }

    public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; } = new List<SurveyAnswer>();

    public virtual ICollection<SurveyOption> SurveyOptions { get; set; } = new List<SurveyOption>();
}