// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class SurveyResult
{
    public int ResultId { get; set; }

    public int? UserId { get; set; }

    public int? SurveyId { get; set; }

    public int? TotalScore { get; set; }

    public DateTime? TakenAt { get; set; }

    public string Recommendation { get; set; }

    public virtual Survey Survey { get; set; }

    public virtual ICollection<SurveyAnswer> SurveyAnswers { get; set; } = new List<SurveyAnswer>();

    public virtual User User { get; set; }
}