// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.Models;

public partial class SurveyAnswer
{
    public int AnswerId { get; set; }

    public int? ResultId { get; set; }

    public int? QuestionId { get; set; }

    public int? OptionId { get; set; }

    public string AnswerText { get; set; }

    public virtual SurveyOption Option { get; set; }

    public virtual SurveyQuestion Question { get; set; }

    public virtual SurveyResult Result { get; set; }
}