// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DrugPrevention.Repositories.DuyenCTT.SoapModels;

[DataContract]
public partial class CourseDuyenCttSoapModel
{
    [DataMember(Order = 1)]
    public int CourseDuyenCttid { get; set; }

    [DataMember(Order = 2)]
    public string Title { get; set; }

    [DataMember(Order = 3)]
    public string Description { get; set; }

    [DataMember(Order = 4)]
    public string TargetGroup { get; set; }

    [DataMember(Order = 5)]
    public bool? IsActive { get; set; }

    [IgnoreDataMember]
    public virtual ICollection<CourseEnrollmentDuyenCttSoapModel> CourseEnrollmentDuyenCtts { get; set; } = new List<CourseEnrollmentDuyenCttSoapModel>();
}
