// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;

namespace DrugPrevention.Repositories.DuyenCTT.SoapModels;

[DataContract]
public class CourseEnrollmentDuyenCttSoapModel
{
    [DataMember(Order = 1)]
    public int EnrollmentDuyenCttid { get; set; }

    [DataMember(Order = 2)]
    public int? UserId { get; set; }

    [DataMember(Order = 3)]
    public int? CourseId { get; set; }

    [DataMember(Order = 4)]
    public DateTime? EnrolledAt { get; set; }

    [DataMember(Order = 5)]
    public int? Progress { get; set; }

    [DataMember(Order = 6)]
    public DateTime? CompletedAt { get; set; }

    [DataMember(Order = 7)]
    public decimal? Score { get; set; }

    [DataMember(Order = 8)]
    public string CertificateUrl { get; set; }

    [DataMember(Order = 9)]
    public bool? IsCertified { get; set; }

    [DataMember(Order = 10)]
    public string EnrollmentSource { get; set; }

    [IgnoreDataMember] // Avoid serializing navigation properties
    public virtual CourseDuyenCttSoapModel Course { get; set; }

    [IgnoreDataMember] // Avoid serializing navigation properties
    public virtual User User { get; set; }
}
