// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.SoapModels;

public partial class ProgramParticipantKhoaNdd
{
    public int ProgramParticipantKhoaNddid { get; set; }

    public int? ProgramId { get; set; }

    public int? UserId { get; set; }

    public DateTime? JoinedAt { get; set; }

    public virtual CommunityProgramKhoaNdd Program { get; set; }

    public virtual User User { get; set; }
}