// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.SoapModels;

public partial class ProgramSurvey
{
    public int ProgramSurveyId { get; set; }

    public int? ProgramId { get; set; }

    public int? SurveyId { get; set; }

    public string Type { get; set; }

    public virtual CommunityProgramKhoaNdd Program { get; set; }

    public virtual SurveyDuongNd Survey { get; set; }
}