// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.SoapModels;

public partial class SurveyAnswerDuongNd
{
    public int AnswerDuongNdid { get; set; }

    public int ResultId { get; set; }

    public int QuestionId { get; set; }

    public int? OptionId { get; set; }

    public string AnswerText { get; set; }

    public decimal? AnswerScore { get; set; }

    public DateTime? AnsweredAt { get; set; }

    public int? TimeSpentOnQuestionSeconds { get; set; }

    public virtual SurveyOptionManhPt Option { get; set; }

    public virtual SurveyQuestionManhPt Question { get; set; }

    public virtual SurveyResultDuongNd Result { get; set; }
}