// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DrugPrevention.Repositories.DuyenCTT.SoapModels;

public partial class SurveyDuongNd
{
    public int SurveyDuongNdid { get; set; }

    public Guid? SurveyGuid { get; set; }

    public string Name { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Purpose { get; set; }

    public string Status { get; set; }

    public int? Version { get; set; }

    public int? CreatedByUserId { get; set; }

    public int? LastModifiedByUserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? LastModifiedAt { get; set; }

    public string TargetAudienceDescription { get; set; }

    public int? EstimatedCompletionTimeMinutes { get; set; }

    public string AnonymityLevel { get; set; }

    public string WelcomeMessage { get; set; }

    public string ThankYouMessage { get; set; }

    public int? ParentSurveyId { get; set; }

    public virtual User CreatedByUser { get; set; }

    public virtual ICollection<SurveyDuongNd> InverseParentSurvey { get; set; } = new List<SurveyDuongNd>();

    public virtual User LastModifiedByUser { get; set; }

    public virtual SurveyDuongNd ParentSurvey { get; set; }

    public virtual ICollection<ProgramSurvey> ProgramSurveys { get; set; } = new List<ProgramSurvey>();

    public virtual ICollection<SurveyAssignment> SurveyAssignments { get; set; } = new List<SurveyAssignment>();

    public virtual ICollection<SurveyQuestionManhPt> SurveyQuestionManhPts { get; set; } = new List<SurveyQuestionManhPt>();

    public virtual ICollection<SurveyResultDuongNd> SurveyResultDuongNds { get; set; } = new List<SurveyResultDuongNd>();
}